# Generated by Django 5.2.15 on 2026-07-25 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_created_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
