# Generated by Django 5.2.15 on 2026-07-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_updated_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='staff_choices',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out Stock', 'Out Stock')], default='In Stock', max_length=20),
        ),
    ]
