# Generated by Django 5.2.15 on 2026-07-29 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_stocktransaction_staff_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='staff_choices',
        ),
    ]
