# Generated by Django 5.2.15 on 2026-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_stocktransaction_staff_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
