# Generated by Django 5.2.15 on 2026-08-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_supplier_created_at_supplier_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.CharField(blank=True, choices=[('reliable', 'Reliable'), ('preferred', 'Preferred'), ('late', 'Late Delivery'), ('blacklisted', 'Blacklisted'), ('new', 'New Supplier')], max_length=30),
        ),
    ]
