# Generated by Django 5.2.15 on 2026-08-06 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_supplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.supplier'),
        ),
    ]
