# Generated by Django 5.2.15 on 2026-08-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_stocktransaction_reference_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('Increase', 'Increase'), ('Decrease', 'Decrease')], help_text='Only used when transaction_type is Adjustment', max_length=10, null=True),
        ),
    ]
