# Generated by Django 5.2.15 on 2026-08-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
    ]
