# Generated by Django 5.2.15 on 2026-09-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='new_product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.product'),
        ),
    ]
