# Generated by Django 5.2.15 on 2026-09-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
